import { User, ParkingSpot, Booking, Wallet, Transaction, Review } from '@/types';
import { generateNextDays, nowISO } from './dateTime';

export const mockUsers: User[] = [
  {
    id: 'user-001',
    name: '张先生',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Felix',
    role: 'owner',
    creditScore: 4.8,
    reviewCount: 23,
    building: '1号楼',
  },
  {
    id: 'user-002',
    name: '李女士',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Lily',
    role: 'owner',
    creditScore: 4.9,
    reviewCount: 31,
    building: '3号楼',
  },
  {
    id: 'user-003',
    name: '王先生',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Wang',
    role: 'renter',
    creditScore: 4.7,
    reviewCount: 15,
    building: '5号楼',
  },
  {
    id: 'user-current',
    name: '我',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Me',
    role: 'renter',
    creditScore: 5.0,
    reviewCount: 8,
    building: '2号楼',
  },
];

const next7Days = generateNextDays(7);

export const mockParkingSpots: ParkingSpot[] = [
  {
    id: 'spot-001',
    ownerId: 'user-001',
    spotNumber: 'A-101',
    building: '1号楼地下',
    description: '靠近电梯口，车位宽敞，适合SUV。白天上班时间空闲。',
    pricePerHour: 5,
    availableDates: [
      { date: next7Days[0], slots: [{ startTime: '08:00', endTime: '18:00' }] },
      { date: next7Days[1], slots: [{ startTime: '08:00', endTime: '18:00' }] },
      { date: next7Days[2], slots: [{ startTime: '08:00', endTime: '18:00' }] },
      { date: next7Days[3], slots: [{ startTime: '08:00', endTime: '18:00' }] },
      { date: next7Days[4], slots: [{ startTime: '08:00', endTime: '18:00' }] },
    ],
    status: 'active',
    avgRating: 4.8,
    reviewCount: 23,
    coverImage: 'https://images.unsplash.com/photo-1590674899484-d5640e854abe?w=600&h=400&fit=crop',
  },
  {
    id: 'spot-002',
    ownerId: 'user-002',
    spotNumber: 'B-205',
    building: '3号楼地下',
    description: '地面停车位，进出方便，适合临时停车。周末全天空闲。',
    pricePerHour: 3,
    availableDates: [
      { date: next7Days[0], slots: [{ startTime: '09:00', endTime: '22:00' }] },
      { date: next7Days[1], slots: [{ startTime: '09:00', endTime: '22:00' }] },
      { date: next7Days[5], slots: [{ startTime: '00:00', endTime: '23:59' }] },
      { date: next7Days[6], slots: [{ startTime: '00:00', endTime: '23:59' }] },
    ],
    status: 'active',
    avgRating: 4.6,
    reviewCount: 18,
    coverImage: 'https://images.unsplash.com/photo-1573348722427-f1d6819fdf98?w=600&h=400&fit=crop',
  },
  {
    id: 'spot-003',
    ownerId: 'user-001',
    spotNumber: 'A-102',
    building: '1号楼地下',
    description: '充电桩车位，支持新能源车充电。工作日晚上和周末可用。',
    pricePerHour: 8,
    availableDates: [
      { date: next7Days[0], slots: [{ startTime: '18:00', endTime: '23:59' }] },
      { date: next7Days[1], slots: [{ startTime: '18:00', endTime: '23:59' }] },
      { date: next7Days[5], slots: [{ startTime: '00:00', endTime: '23:59' }] },
      { date: next7Days[6], slots: [{ startTime: '00:00', endTime: '23:59' }] },
    ],
    status: 'active',
    avgRating: 4.9,
    reviewCount: 45,
    coverImage: 'https://images.unsplash.com/photo-1593941707882-a5bac7201a4a?w=600&h=400&fit=crop',
  },
  {
    id: 'spot-004',
    ownerId: 'user-002',
    spotNumber: 'C-301',
    building: '5号楼地面',
    description: '小区东门附近，进出方便。全天均可预约，长租优惠。',
    pricePerHour: 4,
    availableDates: [
      { date: next7Days[0], slots: [{ startTime: '00:00', endTime: '23:59' }] },
      { date: next7Days[1], slots: [{ startTime: '00:00', endTime: '23:59' }] },
      { date: next7Days[2], slots: [{ startTime: '00:00', endTime: '23:59' }] },
      { date: next7Days[3], slots: [{ startTime: '00:00', endTime: '23:59' }] },
      { date: next7Days[4], slots: [{ startTime: '00:00', endTime: '23:59' }] },
      { date: next7Days[5], slots: [{ startTime: '00:00', endTime: '23:59' }] },
      { date: next7Days[6], slots: [{ startTime: '00:00', endTime: '23:59' }] },
    ],
    status: 'active',
    avgRating: 4.5,
    reviewCount: 12,
    coverImage: 'https://images.unsplash.com/photo-1621929747188-0b4dc28498d2?w=600&h=400&fit=crop',
  },
];

export const mockBookings: Booking[] = [
  {
    id: 'booking-001',
    spotId: 'spot-001',
    renterId: 'user-003',
    ownerId: 'user-001',
    date: next7Days[0],
    startTime: '10:00',
    endTime: '14:00',
    totalCost: 20,
    status: 'completed',
    createdAt: nowISO(),
    spotNumber: 'A-101',
    building: '1号楼地下',
    renterName: '王先生',
    ownerName: '张先生',
    reviewedByRenter: true,
    reviewedByOwner: false,
  },
  {
    id: 'booking-002',
    spotId: 'spot-003',
    renterId: 'user-current',
    ownerId: 'user-001',
    date: next7Days[0],
    startTime: '19:00',
    endTime: '22:00',
    totalCost: 24,
    status: 'active',
    createdAt: nowISO(),
    spotNumber: 'A-102',
    building: '1号楼地下',
    renterName: '我',
    ownerName: '张先生',
    reviewedByRenter: false,
    reviewedByOwner: false,
  },
  {
    id: 'booking-003',
    spotId: 'spot-002',
    renterId: 'user-current',
    ownerId: 'user-002',
    date: next7Days[2],
    startTime: '09:00',
    endTime: '12:00',
    totalCost: 9,
    status: 'pending',
    createdAt: nowISO(),
    spotNumber: 'B-205',
    building: '3号楼地下',
    renterName: '我',
    ownerName: '李女士',
    reviewedByRenter: false,
    reviewedByOwner: false,
  },
];

export const mockWallets: Wallet[] = [
  { id: 'wallet-001', userId: 'user-current', balance: 258.5 },
  { id: 'wallet-002', userId: 'user-001', balance: 320.0 },
  { id: 'wallet-003', userId: 'user-002', balance: 156.5 },
];

export const mockTransactions: Transaction[] = [
  {
    id: 'tx-001',
    walletId: 'wallet-001',
    type: 'deposit',
    amount: 200,
    description: '微信充值',
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: 'tx-002',
    walletId: 'wallet-001',
    type: 'payment',
    amount: -24,
    description: '车位A-102停车费',
    createdAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'tx-003',
    walletId: 'wallet-001',
    type: 'payment',
    amount: -15.5,
    description: '车位B-205停车费',
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'tx-004',
    walletId: 'wallet-001',
    type: 'deposit',
    amount: 100,
    description: '支付宝充值',
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
];

export const mockReviews: Review[] = [
  {
    id: 'review-001',
    bookingId: 'booking-001',
    fromUserId: 'user-003',
    toUserId: 'user-001',
    rating: 5,
    comment: '车位位置很好找，业主很热情，下次还来！',
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    fromUserName: '王先生',
  },
  {
    id: 'review-002',
    bookingId: 'booking-001',
    fromUserId: 'user-001',
    toUserId: 'user-003',
    rating: 5,
    comment: '准时离开，车位保护得很好，靠谱的邻居！',
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    fromUserName: '张先生',
  },
];
